#Requires -Version 7.0
<#
.SYNOPSIS
    Generates .env.ps1 from .env and syncs .env to GitHub Actions repository variables and secrets.
.EXAMPLE
    ./scripts/Sync-Environment.ps1
.EXAMPLE
    ./scripts/Sync-Environment.ps1 -SkipGitHub
#>
[CmdletBinding()]
param(
    [string]$EnvFile = (Join-Path $PSScriptRoot '..' '.env'),
    [switch]$SkipGitHub,
    [string]$Repo
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$localOnlyKeys = @('RELEASE_NOTES_API_URL', 'FUNCTION_KEY')
$secretPattern = 'SECRET|TOKEN|PASSWORD|KEY'

if (-not (Test-Path $EnvFile)) {
    throw "Environment file '$EnvFile' not found. Create it using the keys in .env.example.ps1."
}

$entries = [ordered]@{}
foreach ($line in Get-Content -Path $EnvFile) {
    $trimmed = $line.Trim()
    if (-not $trimmed -or $trimmed.StartsWith('#')) { continue }
    $separator = $trimmed.IndexOf('=')
    if ($separator -lt 1) {
        Write-Warning "Skipping malformed line: $($trimmed.Split('=')[0])"
        continue
    }
    $key = $trimmed.Substring(0, $separator).Trim()
    $value = $trimmed.Substring($separator + 1).Trim()
    if ($value.Length -ge 2 -and (($value[0] -eq '"' -and $value[-1] -eq '"') -or ($value[0] -eq "'" -and $value[-1] -eq "'"))) {
        $value = $value.Substring(1, $value.Length - 2)
    }
    $entries[$key] = $value
}

$psFile = Join-Path (Split-Path -Parent (Resolve-Path $EnvFile)) '.env.ps1'
$output = @('# Generated by scripts/Sync-Environment.ps1 from .env. Do not edit; edit .env and re-run the script.')
foreach ($key in $entries.Keys) {
    $output += "`$env:$key = '$($entries[$key].Replace("'", "''"))'"
}
Set-Content -Path $psFile -Value $output -Encoding utf8
Write-Host "Wrote $psFile ($($entries.Count) keys)."

if ($SkipGitHub) { return }

gh auth status *> $null
if ($LASTEXITCODE -ne 0) {
    throw 'GitHub CLI is not authenticated. Run "gh auth login" and re-run this script.'
}

$repoArgs = if ($Repo) { @('--repo', $Repo) } else { @() }
foreach ($key in $entries.Keys) {
    if ($key -in $localOnlyKeys) {
        Write-Host "Skipping local-only key $key."
        continue
    }
    $value = $entries[$key]
    if (-not $value) {
        Write-Host "Skipping empty key $key."
        continue
    }
    if ($key -match $secretPattern) {
        $value | gh secret set $key @repoArgs
        if ($LASTEXITCODE -ne 0) { throw "Failed to set secret $key." }
        Write-Host "Set secret $key."
    }
    else {
        gh variable set $key --body $value @repoArgs
        if ($LASTEXITCODE -ne 0) { throw "Failed to set variable $key." }
        Write-Host "Set variable $key."
    }
}
